name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup OCaml
      uses: avsm/setup-ocaml@v2
    - name: Install
      run: opam install -y .
